### PR TITLE
Made a bunch of changes (see description)

### PR DESCRIPTION
**Pull request by Gip-Gip**
* Fixed frontend_version so it prints the native comment instead of a semicolon
* Fixed lines going over 80 characters
* Fixed single line comments so they work on Turbo C 1.0
* Added log support
* Added a less-annoying omni-puts(oputs) that writes to both stderr and the log

### CODE REVIEW

**Comment by ncb85** [comment]
Hi, I used a preprocessor to make it compile on Turbo C2.0. There are one line comments in remaining files as well. You need to change them as well. (or use preprocessor when building on TurboC)

**Comment by Gip-Gip** [comment]
I'm just going through the files cleaning everything up, all the comments should be C89-compatable by the time I'm through

**Comment by ncb85** [comment]
I am prone to merge your changes when you are done. But please resolve that WARNING. So far it has compiled silently and let's keep it that way.

**Comment by Gip-Gip** [comment]
No problem

**Comment by Gip-Gip** [comment]
I'm not going to be done with the backend for quite a while, so go ahead and merge

**Pull request merged**
